version: "3"
services:
    database:
        image: mysql:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: tracks
    account:
        image: php:apache
        ports:
            - 8090:80
        volumes:
            - ./code:/var/www/html
