version: "3"
services:
    database:
        image: mysql:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: tracks
    account:
        image: keloran/dockerphp
        ports:
            - 8090:80
        volumes:
            - ./code:/var/www
            - ./code/public:/var/www/html
